"""Self-introspection: what Emma can do, told to the user.

The CLAUDE.md "Self-aware" principle says Emma maintains
``self/capabilities.md`` from the live tool registry and answers
"what can you do?" from that file, not from a hard-coded list.

This module:

1. Regenerates ``self/capabilities.md`` from the registered tools on
   first discovery (called by ``tools.registry._discover``).
2. Exposes ``describe_capabilities`` as a voice-callable tool that
   reads the file back and speaks a short summary.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import structlog

from tools.base import ToolResult, tool

log = structlog.get_logger("emma.tools.self")

REPO_ROOT = Path(__file__).resolve().parent.parent
CAPABILITIES_PATH = REPO_ROOT / "self" / "capabilities.md"


def regenerate_capabilities_md() -> None:
    """Write ``self/capabilities.md`` from the current registry.

    Idempotent; safe to call multiple times. Intentionally avoids
    importing :mod:`tools.registry` at module load to dodge import
    cycles - we read the live registry off ``tools.base.get_registry``.
    """
    try:
        from tools.base import get_registry
    except Exception as exc:
        log.warning("self_capabilities_regen_import_failed", error=str(exc))
        return

    registry = get_registry()
    # De-duplicate aliases: only emit each canonical name once.
    seen: set[str] = set()
    rows: list[tuple[str, str]] = []
    for _name, entry in sorted(registry.items()):
        if entry.name in seen:
            continue
        seen.add(entry.name)
        desc = (entry.description or "").strip().split("\n", 1)[0]
        rows.append((entry.name, desc or "(no description)"))

    if not rows:
        # First-startup race: registry not populated yet. Leave the
        # existing file alone rather than overwriting it with empty
        # state - registry._discover will call us again after import.
        return

    now = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    lines: list[str] = [
        "<!-- Auto-generated by tools/self_tool.py at startup. Do not edit by hand. -->",
        f"<!-- Generated: {now} -->",
        "",
        "# Emma capabilities",
        "",
        f"Emma has {len(rows)} registered tools.",
        "",
        "| Tool | What it does |",
        "| --- | --- |",
    ]
    for name, desc in rows:
        # Markdown-table-safe: collapse pipes/newlines in the description.
        safe_desc = desc.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{name}` | {safe_desc} |")
    lines.append("")
    try:
        CAPABILITIES_PATH.parent.mkdir(parents=True, exist_ok=True)
        CAPABILITIES_PATH.write_text("\n".join(lines))
        log.info("self_capabilities_written", count=len(rows), path=str(CAPABILITIES_PATH))
    except Exception as exc:
        log.warning("self_capabilities_write_failed", error=str(exc))


@tool()
def describe_capabilities() -> ToolResult:
    """Tell the user what Emma can do, in one or two short spoken sentences.

    Use when the user says any of:

    - "Emma, ¿qué puedes hacer?"
    - "¿de qué eres capaz?"
    - "what can you do?"
    - "describe your capabilities"

    Pulls from ``self/capabilities.md`` (regenerated at startup from the
    live tool registry). Returns the structured list in ``data`` and a
    spoken-friendly summary in ``user_message``.
    """
    if not CAPABILITIES_PATH.exists():
        return ToolResult(
            True,
            {"tools": []},
            "Aún estoy arrancando; en un momento te puedo decir.",
            False,
        )
    try:
        text = CAPABILITIES_PATH.read_text()
    except Exception as exc:
        return ToolResult(False, None, f"No pude leer mi propio archivo: {exc}", False)

    tool_names: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("| `") and "` |" in line:
            name = line.split("`", 2)[1]
            tool_names.append(name)

    if not tool_names:
        return ToolResult(
            True,
            {"tools": []},
            "Mi archivo de capacidades está vacío.",
            False,
        )

    categories = _summarize_for_voice(tool_names)
    msg = (
        f"Puedo: {categories}. En total tengo {len(tool_names)} herramientas. "
        "Si me pides algo específico te digo si puedo o no."
    )
    return ToolResult(
        True,
        {"tools": tool_names, "count": len(tool_names)},
        msg,
        False,
    )


def _summarize_for_voice(tool_names: list[str]) -> str:
    """Map raw tool names to a short, spoken list of categories."""

    def has(*prefixes: str) -> bool:
        return any(any(t.startswith(p) for p in prefixes) for t in tool_names)

    bits: list[str] = []
    if has("play_", "pause", "resume", "next_track", "previous_track", "now_playing"):
        bits.append("controlar música")
    if has("latest_video", "search_and_open"):
        bits.append("abrir videos de YouTube")
    if has("set_volume", "mute", "unmute"):
        bits.append("ajustar el volumen")
    if has("set_brightness"):
        bits.append("cambiar el brillo")
    if has("sleep_display", "lock_screen"):
        bits.append("apagar pantalla o bloquear")
    if has("current_time"):
        bits.append("decir la hora")
    if has("open_application"):
        bits.append("abrir apps")
    if has("search_web", "summarize_page"):
        bits.append("buscar en la web y resumir páginas")
    if has("open_url"):
        bits.append("abrir enlaces")
    if has("browser_navigate", "browser_click", "browser_do"):
        bits.append("automatizar el navegador")
    if has("remember_fact", "recall_facts", "forget_fact"):
        bits.append("recordar cosas sobre ti")
    if has("set_preferred_app", "get_preferred_app", "set_default_browser"):
        bits.append("guardar tus preferencias de apps")
    if has("health_check", "describe_my_health"):
        bits.append("hacerme un diagnóstico")
    if has("open_workspace"):
        bits.append("abrir mi propio código para que me edites")
    if not bits:
        return "varias cosas"
    return ", ".join(bits)
